# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qt/server_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from concurrent.futures import thread
import threading
from PyQt5 import QtCore, QtGui, QtWidgets
import server_logik

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 20, 281, 121))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnTest = QtWidgets.QPushButton(self.centralwidget)
        self.btnTest.setGeometry(QtCore.QRect(100, 280, 181, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnTest.setFont(font)
        self.btnTest.setObjectName("btnTest")
        self.btnTest.clicked.connect(self.sende_klingelsignal)
        self.btnStartServer = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartServer.setGeometry(QtCore.QRect(420, 280, 181, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnStartServer.setFont(font)
        self.btnStartServer.setObjectName("btnStartServer")
        self.btnStartServer.clicked.connect(self.start_server)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SERVER"))
        self.btnTest.setText(_translate("MainWindow", "TEST"))
        self.btnStartServer.setText(_translate("MainWindow", "START SERVER"))

    def start_server(self):
        try:
            server_thread = threading.Thread(target=server_logik.starte_server) # seperaten Thread für server logik starten
            server_thread.start()
        except:
            print("Error: Problem beim Starten des Servers")

    def sende_klingelsignal(self):
        server_logik.sende_klingelsignal_an_clients()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
